services:
  - type: web
    name: my-chess-game
    env: static
    routes:
      # यह नियम सबसे ऊपर होना चाहिए ताकि गेम खुलने से पहले फ़ाइल मिल जाए
      - type: rewrite
        src: /.well-known/assetlinks.json
        path: /assetlinks.json
      # इसके नीचे आपके गेम का पुराना रूट रहेगा (अगर कोई है तो)
